---
title: "Read new simulation results data"
output: html_document
date: "2025-04-03"
---

### Read datafile
```{r}
library(tidyverse)
library(papaja)
combined_results = read_csv("0505/combined_results_contaminants.csv")
```




```{r}
large_effects = combined_results %>% 
  filter(effect_size == "large_effect")

small_effects = combined_results %>% 
  filter(effect_size == "small_effect")

large_no_effects = combined_results %>% 
  filter(effect_size == "large_no_effect")

small_no_effects = combined_results %>% 
  filter(effect_size == "small_no_effect")
```

# Large effect read
```{r}
convergence_large = large_effects %>% 
  group_by(model_id) %>% 
  summarize(converged = mean(ifelse(convergence_status == "Converged", 1, 0))) %>% 
  filter(converged>0) %>% 
  pivot_wider(names_from = model_id, values_from = converged) %>% 
  mutate(dataset = "prime_probe")

convergence_small = small_effects %>% 
 group_by(model_id) %>% 
  summarize(converged = mean(ifelse(convergence_status == "Converged", 1, 0))) %>% 
  filter(converged>0) %>% 
  pivot_wider(names_from = model_id, values_from = converged) %>% 
  mutate(dataset = "flanker")

convergence_small_no = small_no_effects %>% 
 group_by(model_id) %>% 
  summarize(converged = mean(ifelse(convergence_status == "Converged", 1, 0))) %>% 
  filter(converged>0) %>% 
  pivot_wider(names_from = model_id, values_from = converged) %>% 
  mutate(dataset = "prime_probe_no_effect")

convergence_large_no = large_no_effects %>% 
  group_by(model_id) %>% 
  summarize(converged = mean(ifelse(convergence_status == "Converged", 1, 0))) %>% 
  filter(converged>0) %>% 
  pivot_wider(names_from = model_id, values_from = converged) %>% 
  mutate(dataset = "flanker_no_effect")

convergence_table = rbind(convergence_large, convergence_small, convergence_large_no, convergence_small_no)

View(apa_table(convergence_table, caption = "A summary table of the cars dataset."))

flextable::flextable(convergence_table)

```

```{r}
large_summary_table_models = large_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(model_id, participants) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )
```
```{r}
large_summary_model_results = large_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(model_id) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )
large_summary_model_results
```

```{r}
large_summary_plot_models = large_summary_table_models %>% 
  ggplot() +
  aes(x=participants, y=TPR, group = model_id, color = model_id)+
  geom_point()+
  geom_path(alpha = .6) +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()

large_summary_plot_models
ggsave("all_models.png", dpi = 600, width = 8, height = 4)
```

#### NOEFFECT

```{r}
large_no_effects = combined_results %>% 
  filter(effect_size == "large_no_effect")

no_large_summary_table_models = large_no_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(model_id, participants) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )

no_large_summary_results = large_no_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(model_id) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )
no_large_summary_results
```


```{r}
no_large_summary_plot_models = no_large_summary_table_models %>% 
  ggplot() +
  aes(x=participants, y=FPR, group = model_id, color = model_id)+
  geom_point()+
  geom_path() +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()

no_large_summary_plot_models
ggsave("no_all_models.png", dpi = 600, width = 8, height = 4)
```

## NO FILTER MODELS
```{r}
large_summary_table_models_nofilter = large_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova",
         filter_type == "no_filter") %>% 
  group_by(model_id, participants) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )
```
```{r}
large_summary_models_nofilter_results = large_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova",
         filter_type == "no_filter") %>% 
  group_by(model_id) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )
large_summary_models_nofilter_results
```

```{r}
large_summary_plot_models_nofilter = large_summary_table_models_nofilter %>% 
  ggplot() +
  aes(x=participants, y=TPR, group = model_id, color = model_id)+
  geom_point()+
  geom_path(alpha = .6) +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()

large_summary_plot_models_nofilter
ggsave("all_models_nofilter.png", dpi = 600, width = 8, height = 4)
```

#### NOEFFECT

```{r}

no_large_summary_table_models_nofilter = large_no_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova",
         filter_type == "no_filter") %>% 
  group_by(model_id, participants) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )

no_large_summary_results_nofilter = large_no_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova",
         filter_type == "no_filter") %>% 
  group_by(model_id) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )
no_large_summary_results_nofilter
```


```{r}
no_large_summary_plot_models_nofilter = no_large_summary_table_models_nofilter %>% 
  ggplot() +
  aes(x=participants, y=FPR, group = model_id, color = model_id)+
  geom_point()+
  geom_path() +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()

no_large_summary_plot_models_nofilter
ggsave("no_all_models_nofilter.png", dpi = 600, width = 8, height = 4)
```

### 3.0SD FILTER MODELS
```{r}
large_summary_table_models_3 = large_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova",
         filter_type == "sd_3.0") %>% 
  group_by(model_id, participants) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )
```
```{r}
large_summary_models_3_results = large_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova",
         filter_type == "sd_3.0") %>% 
  group_by(model_id) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )
large_summary_models_3_results
```

```{r}
large_summary_plot_models_3 = large_summary_table_models_3 %>% 
  ggplot() +
  aes(x=participants, y=TPR, group = model_id, color = model_id)+
  geom_point()+
  geom_path(alpha = .6) +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()

large_summary_plot_models_3
ggsave("all_models_3.png", dpi = 600, width = 8, height = 4)
```

#### NOEFFECT

```{r}

no_large_summary_table_models_3 = large_no_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova",
         filter_type == "sd_3.0") %>% 
  group_by(model_id, participants) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )

no_large_summary_results_3 = large_no_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova",
         filter_type == "sd_3.0") %>% 
  group_by(model_id) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )
no_large_summary_results_3
```


```{r}
no_large_summary_plot_models_3 = no_large_summary_table_models_3 %>% 
  ggplot() +
  aes(x=participants, y=FPR, group = model_id, color = model_id)+
  geom_point()+
  geom_path() +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()

no_large_summary_plot_models_3
ggsave("no_all_models_3.png", dpi = 600, width = 8, height = 4)
```


# OUTLIER FILTERS

```{r}
large_summary_table_filters = large_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(filter_type, participants) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )

```
```{r}
large_summary_table_filters_results = large_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(filter_type) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )
large_summary_table_filters_results
```

```{r}
large_summary_plot_filters = large_summary_table_filters %>% 
  ggplot() +
  aes(x=participants, y=TPR, group = filter_type, color = filter_type)+
  geom_point()+
  geom_path() +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()
large_summary_plot_filters
ggsave("all_filters.png", dpi = 600, width = 8, height = 4)
```

### NO EFFECT
```{r}
no_large_summary_table_filters = large_no_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(filter_type, participants) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )

```
```{r}
no_large_summary_table_filters_results = large_no_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(filter_type) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )
no_large_summary_table_filters_results
```
### All combinations
```{r}
large_summary_results = large_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(model_id, filter_type) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )

large_summary_results
```
```{r}
no_large_summary_table_results = large_no_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(model_id,filter_type) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )
no_large_summary_table_results
```


### small effect read

```{r}
small_summary_table_models = small_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(model_id, participants) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )

small_summary_table_models_results = small_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(model_id) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )
small_summary_table_models_results
```
```{r}
small_summary_models_plot = small_summary_table_models %>% 
ggplot() +
  aes(x=participants, y=TPR, group = model_id, color = model_id)+
  geom_point()+
  geom_path(alpha = .6) +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()

small_summary_models_plot
ggsave(plot=small_summary_models_plot,"small_models.png", dpi = 600, width = 8, height = 4)
```

#### NO EFFECT
```{r}
small_no_summary_table_models = small_no_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(model_id, participants) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )

small_no_summary_table_models_results = small_no_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(model_id) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )
small_no_summary_table_models_results
```
```{r}
no_small_summary_models_plot = small_no_summary_table_models %>% 
ggplot() +
  aes(x=participants, y=FPR, group = model_id, color = model_id)+
  geom_point()+
  geom_path(alpha = .6) +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()

no_small_summary_models_plot
ggsave(plot=no_small_summary_models_plot,"no_small_models.png", dpi = 600, width = 8, height = 4)
```


## NOFILTER SMALL
```{r}
small_summary_table_models_nofilter = small_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  filter(filter_type == "no_filter") %>% 
  group_by(model_id, participants) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )

small_summary_table_models_results_nofilter = small_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  filter(filter_type == "no_filter") %>% 
  group_by(model_id) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )
small_summary_table_models_results_nofilter
```

```{r}
small_summary_models_plot_nofilter = small_summary_table_models_nofilter %>% 
ggplot() +
  aes(x=participants, y=TPR, group = model_id, color = model_id)+
  geom_point()+
  geom_path(alpha = .6) +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()

small_summary_models_plot_nofilter
ggsave(plot=small_summary_models_plot_nofilter,"small_models_nofilter.png", dpi = 600, width = 8, height = 4)

```

#### NO EFFECT
```{r}
no_small_summary_table_models_nofilter = small_no_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  filter(filter_type == "no_filter") %>% 
  group_by(model_id, participants) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )

no_small_summary_table_models_results_nofilter = small_no_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  filter(filter_type == "no_filter") %>% 
  group_by(model_id) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )
no_small_summary_table_models_results_nofilter
```

```{r}
no_small_summary_models_plot_nofilter = no_small_summary_table_models_nofilter %>% 
ggplot() +
  aes(x=participants, y=FPR, group = model_id, color = model_id)+
  geom_point()+
  geom_path(alpha = .6) +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()

no_small_summary_models_plot_nofilter
ggsave(plot=no_small_summary_models_plot_nofilter,"no_small_models_nofilter.png", dpi = 600, width = 8, height = 4)

```
## 3.0SD SMALL
```{r}
small_summary_table_models_3 = small_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  filter(filter_type == "sd_3.0") %>% 
  group_by(model_id, participants) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )

small_summary_table_models_results_3 = small_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  filter(filter_type == "sd_3.0") %>% 
  group_by(model_id) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )
small_summary_table_models_results_3
```

```{r}
small_summary_models_plot_3 = small_summary_table_models_3 %>% 
ggplot() +
  aes(x=participants, y=TPR, group = model_id, color = model_id)+
  geom_point()+
  geom_path(alpha = .6) +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()

small_summary_models_plot_3
ggsave(plot=small_summary_models_plot_3,"small_models_3.png", dpi = 600, width = 8, height = 4)

```

#### NO EFFECT
```{r}
no_small_summary_table_models_3 = small_no_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  filter(filter_type == "sd_3.0") %>% 
  group_by(model_id, participants) %>% 
   summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )

no_small_summary_table_models_results_3 = small_no_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  filter(filter_type == "sd_3.0") %>% 
  group_by(model_id) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )
no_small_summary_table_models_results_3
```

```{r}
no_small_summary_models_plot_3 = no_small_summary_table_models_3 %>% 
ggplot() +
  aes(x=participants, y=FPR, group = model_id, color = model_id)+
  geom_point()+
  geom_path(alpha = .6) +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()

no_small_summary_models_plot_3
ggsave(plot=no_small_summary_models_plot_3,"no_small_models_3.png", dpi = 600, width = 8, height = 4)

```

#### OUTLIER FILTERS


```{r}
small_summary_table_filters = small_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(filter_type, participants) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )

```
```{r}
small_summary_table_filters_results = small_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(filter_type) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )
small_summary_table_filters_results
```

```{r}
small_summary_plot_filters = small_summary_table_filters %>% 
  ggplot() +
  aes(x=participants, y=TPR, group = filter_type, color = filter_type)+
  geom_point()+
  geom_path() +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()
small_summary_plot_filters
ggsave(plot = small_summary_plot_filters, "small_filters.png", dpi = 600, width = 8, height = 4)
```

### NO EFFECT
```{r}
no_small_summary_table_filters = small_no_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(filter_type, participants) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )

```
```{r}
no_small_summary_table_filters_results = small_no_effects %>% 
  filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(filter_type) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )
no_small_summary_table_filters_results
```
```{r}
no_small_summary_plot_filters = no_small_summary_table_filters %>% 
  ggplot() +
  aes(x=participants, y=FPR, group = filter_type, color = filter_type)+
  geom_point()+
  geom_path() +
  ylim(0,1)+
  scale_color_discrete(name = "Model Type", 
                       labels = c("anova" = "ANOVA",
                                  "full_lmer" = "complex LMM",
                                  "simple_lmer" = "simple LMM",
                                  "simple_log_lmer" = "simple LMM with log(RT)",
                                  "full_log_lmer" = "complex LMM with log(RT)"))+
  scale_x_continuous(breaks = c(25, 50, 100, 200, 400))+
  papaja::theme_apa()
no_small_summary_plot_filters
ggsave(plot = no_small_summary_plot_filters, "no_small_filters.png", dpi = 600, width = 8, height = 4)
```
### all combinations small
```{r}
small_summary_table_results = small_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(model_id,filter_type) %>% 
  summarize(N = n(),
            TPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = TPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = TPR+1.96*(evidence_sd/sqrt(N))
            )
small_summary_table_results
```
no effect
```{r}
small_no_summary_table_results = small_no_effects %>% 
   filter(convergence_status == "Converged" | model_id == "anova") %>% 
  group_by(model_id,filter_type) %>% 
  summarize(N = n(),
            FPR = mean(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            evidence_sd = sd(ifelse(model_id == 'anova', ifelse(p.value<.05, 1, 0), ifelse(evidence,1,0)), na.rm = T),
            lower_ci = FPR-1.96*(evidence_sd/sqrt(N)),
            upper_ci = FPR+1.96*(evidence_sd/sqrt(N))
            )
small_no_summary_table_results
```


```{r}
small_roc_data = small_summary_table %>% 
  left_join(., no_summary_table, by="model_id")
```

## NO summary read


```{r}
library(qs)
sampledata1 =qread("results/0505/large_effect_sample.qs")
sampledata2 = qread("sampled_files/sampled_files/small_effect/200_0589.qs")
```


```{r}
participants = sampledata1 %>% 
  group_by(participant_id) %>% 
  summarize(meanrt = mean(diffusion_rt, na.rm = T),
            sdrt = sd(diffusion_rt))

sd(sampledata1$diffusion_rt)

hist(sampledata1$diffusion_rt)

csedata = sampledata1 %>% 
  group_by(prev_congruent, is_congruent) %>% 
  summarize(meanrt = mean(diffusion_rt, na.rm = T))

csedata %>% ggplot() +
  aes(x=prev_congruent, y = meanrt, group = is_congruent, color = is_congruent) +
  geom_point()+
  geom_path()
```
```{r}
primprob = read_csv("obtained/primeprobe_processed.csv")

hist(primprob$rt)
```

```{r}
library(lme4)
library(ez)
mymodel = lmer(diffusion_rt ~ is_congruent + is_congruent:prev_congruent + (1 | participant_id), data = sampledata1)
summary(mymodel)

csedatasummary = sampledata1 %>% 
  group_by(participant_id, prev_congruent, is_congruent) %>% 
  summarize(meanrt = mean(diffusion_rt),
            N = n())

test = csedatasummary %>% group_by(participant_id) %>% summarize(condn = n())

(II-IC)<(CI-CC)

summary(aov(meanrt ~ as.factor(is_congruent) + as.factor(is_congruent)*as.factor(prev_congruent) + Error(1/participant_id), data = csedatasummary))

myanova = ezANOVA(data = csedatasummary, dv = meanrt, wid = participant_id, within = .(is_congruent, prev_congruent))
```

